name: Debug Github workflow

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
env:
  DATAFLOW_GITHUB_IDENTITY_PROVIDER: "projects/405065206937/locations/global/workloadIdentityPools/dataflow-github-actions-pool/providers/dataflow-github-actions-provider"
  DATAFLOW_GITHUB_SERVICE_ACCOUNT: "dataflow-github-actions-user@lam-bo-home-music.iam.gserviceaccount.com"

jobs:
  workflow-debug:
    name: Debug image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Get GCP token
        id: auth
        uses: google-github-actions/auth@v0.5.0
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ env.DATAFLOW_GITHUB_IDENTITY_PROVIDER }}
          service_account: ${{ env.DATAFLOW_GITHUB_SERVICE_ACCOUNT }}

      - name: Print token
        run: |
          echo "Token: ${{ env.auth.outputs.access_token }}"
